#<-----------------Arthimatic operator-------------------->

#addition operator
def addition(x,y):
    return x+y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(addition(n1,n2)) #16

#subtraction operator
def subtraction(x,y):
    return x-y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(subtraction(n1,n2)) #-1

#multiplication operator
def multiplication(x,y):
    return x*y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(multiplication(n1,n2)) #204

#division operator
def division(x,y):
    return x/y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(division(n1,n2)) #2.875

#module operator
def module(x,y):
    return x%y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(module(n1,n2)) #2

#power operator
def power(x,y):
    return x**y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(power(n1,n2)) #9

#integer division operator
def integerdivision(x,y):
    return x//y
n1 = int(input('Enter 1st number : '),10)
n2 = int(input('Enter 2nd number : '),10)
print(integerdivision(n1,n2)) #1
